//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.0.8.0 (NJsonSchema v11.0.1.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------

/* tslint:disable */
/* eslint-disable */
// ReSharper disable InconsistentNaming



export interface GetUsersResponse {
    userList: User[];

    [key: string]: any;
}

export interface GetPaymentsResponse {
    payments: Payment[];

    [key: string]: any;
}

export interface PostPaymentRequest {
    payment: PostPayment;

    [key: string]: any;
}

export interface User {
    id: number;
    email: string;
    firstName: string;
    lastName: string;

    [key: string]: any;
}

export interface Payment {
    /** resource id of the payment */
    paymentId: number;
    paymentDescription: string;
    /** date of the payment */
    paymentDate: Date;
    price: number;
    debitors: string[];
    creditor: string;
    author: string;
    updateTime: Date;

    [key: string]: any;
}

export interface PostPayment {
    paymentDescription: string;
    /** date of the payment */
    paymentDate: Date;
    price: number;
    debitors: string[];
    creditor: string;
    /** email of the user who created this payment */
    author: string;

    [key: string]: any;
}